import type { Locale } from "./types";

export const copy = {
  bg: {
    brand: "Prima16 Допълнителни",
    stamp: "ДОПЪЛНИТЕЛНИ",
    short: "Допълнителни",
    titleSuffix: "Prima16 Extras",
    navHome: "Начало",
    navChange: "Протокол",
    navTm: "Труд и материали",
    navPricing: "Цени",
    navFaq: "Въпроси",
    navExamples: "Примери",
    navJobs: "Обект",
    langBg: "БГ",
    langEn: "EN",
    heroTitle: "Допълнителната работа изчезва в Viber. Сложи я в номериран PDF.",
    heroSub:
      "Prima16 Допълнителни прави протокол за допълнителни работи или билет труд-и-материали. По желание пази обекта и новата стойност по договора.",
    heroCta: "Нов протокол",
    heroSecondary: "Виж примерен PDF",
    heroTm: "Билет труд и материали",
    relation: "Инструмент на Prima16 — не е абонамент за фактуриране.",
    howTitle: "Как работи",
    how1t: "Попълваш формуляра",
    how1d: "Страни, обект, редове. Без акаунт.",
    how2t: "Изтегляш A4",
    how2d: "Номер, дата, сума. Готово за подпис на обекта.",
    how3t: "Плащаш само ако махнеш колонтитула",
    how3d: "€1.99 за този вид на това устройство. Без абонамент.",
    notTitle: "Какво не е",
    notItems: [
      "Не е данъчна фактура и не е оферта.",
      "Не е правен, данъчен или счетоводен съвет.",
      "Не е Документи — там са оферти и протоколи по доставка.",
      "Не е AIA и не е ServiceTitan.",
    ],
    toolsTitle: "Два шаблона",
    coCardT: "Допълнително възлагане",
    coCardD: "Добавяне, приспадане или само срок. Блок с нова стойност по договора.",
    tmCardT: "Труд и материали",
    tmCardD: "Часове, ставки, материали. За работа без твърда цена.",
    footerFamily:
      "Prima16 Extras е инструмент на Prima16. Други инструменти: Документи · RenoBudget (скоро)",
    footerPdf: "Създадено с Prima16 Extras • extras.prima16.com",
    disclaimer:
      "Това е бизнес шаблон от Prima16 Extras. Не е правна, данъчна или счетоводна консултация и не е данъчна фактура.",
    formTitleCo: "Протокол за допълнителни работи",
    formTitleTm: "Билет труд и материали",
    fieldNumber: "Номер",
    fieldDate: "Дата",
    fieldKind: "Вид",
    kindAdd: "Добавяне",
    kindDeduct: "Приспадане",
    kindSchedule: "Само срок",
    fieldPaper: "Хартия",
    fieldCurrency: "Валута",
    fieldContractor: "Изпълнител",
    fieldClient: "Възложител",
    fieldDetails: "Адрес, ЕИК, телефон",
    fieldSite: "Обект",
    fieldContract: "Договор / оферта №",
    fieldOriginal: "Първоначална стойност",
    fieldPrev: "Предишни допълнителни",
    fieldReason: "Основание / описание",
    fieldSchedule: "Влияние върху срока",
    fieldNotes: "Бележки",
    linesTitle: "Редове",
    colDesc: "Описание",
    colQty: "Кол.",
    colUnit: "Мярка",
    colPrice: "Ед. цена",
    colTotal: "Сума",
    addLine: "Ред",
    fromBook: "От ценоразпис",
    saveBook: "Запази в ценоразпис",
    recTitle: "Стойност по договора",
    recOriginal: "Първоначален договор",
    recPrev: "Предишни допълнителни",
    recThis: "Този документ",
    recRevised: "Нова стойност",
    recHidden: "Няма въведена първоначална стойност — блокът е скрит в PDF.",
    draft: "Чернова",
    finalize: "Финализирай и изтегли PDF",
    download: "Изтегли PDF",
    print: "Печат / PDF",
    saveJob: "Запази към обекта",
    newDoc: "Нова чернова",
    loadSample: "Зареди пример",
    footerOn: "С колонтитул Prima16 Extras",
    footerOff: "Чист PDF — колонтитулът е махнат на това устройство",
    unlockTitle: "Махни колонтитула",
    unlockOne: "Чист PDF за този вид — €1.99 веднъж",
    unlockAll: "Това устройство, всички шаблони — €19.99 веднъж",
    unlockNote:
      "Поръчката се обработва от Paddle.com като търговец по сделката. 30 дни за връщане. Не отключва docs.prima16.com.",
    unlockDemo: "Демо плащане (sandbox)",
    unlockDone: "Отключено на това устройство.",
    quota: "Безплатни финални PDF този месец",
    quotaBlock: "Достигнат е лимитът от 2 безплатни финални PDF за месеца. Плати или изчакай следващия месец.",
    jobTitle: "Локален обект",
    jobHint: "Един незаписан в облак обект в този браузър. Черновите не пипат сумата. Финалните я пипат.",
    jobName: "Име на обекта",
    jobRevised: "Текуща нова стойност",
    emptyJob: "Няма запазен обект.",
    pricebookTitle: "Ценоразпис",
    emptyBook: "Празен ценоразпис. Запази ред от формуляра.",
    pricingTitle: "Цени",
    pricingLead:
      "Същият файл. Платената версия маха реда Prima16 Extras в колонтитула. Плащаш на екрана за изтегляне. Paddle.com е търговец по сделката. 30 дни за връщане.",
    faqTitle: "Въпроси",
    vsTitle: "Защо не Excel",
    legalTerms: "Общи условия",
    legalPrivacy: "Поверителност",
    legalDisclaimer: "Отказ от отговорност",
    legalRefunds: "Връщания",
    support: "Пишете на",
    examplesTitle: "Примери",
    blogTitle: "Бележки",
    samplePdf: "Примерен лист",
  },
  en: {
    brand: "Prima16 Extras",
    stamp: "EXTRAS",
    short: "Extras",
    titleSuffix: "Prima16 Extras",
    navHome: "Home",
    navChange: "Change order",
    navTm: "T&M ticket",
    navPricing: "Pricing",
    navFaq: "FAQ",
    navExamples: "Examples",
    navJobs: "Job file",
    langBg: "BG",
    langEn: "EN",
    heroTitle: "Extra work disappears in the chat. Put it on a numbered PDF.",
    heroSub:
      "Prima16 Extras is a change-order and T&M generator for trades. Optional job file. Running contract total. A4 download.",
    heroCta: "New change order",
    heroSecondary: "View sample PDF",
    heroTm: "New T&M ticket",
    relation: "A Prima16 tool — not an invoicing subscription.",
    howTitle: "How it works",
    how1t: "Fill the form",
    how1d: "Parties, site, lines. No account.",
    how2t: "Download A4",
    how2d: "Number, date, amount. Ready to sign on site.",
    how3t: "Pay only to drop the footer",
    how3d: "€1.99 for this type on this device. No subscription.",
    notTitle: "What it is not",
    notItems: [
      "Not a VAT invoice and not a quote.",
      "Not legal, tax or accounting advice.",
      "Not Документи — quotes and delivery notes live there.",
      "Not AIA and not ServiceTitan.",
    ],
    toolsTitle: "Two templates",
    coCardT: "Change order",
    coCardD: "Add, deduct, or schedule only. Contract reconciliation block.",
    tmCardT: "Time & materials",
    tmCardD: "Hours, rates, materials. For work without a lump sum.",
    footerFamily:
      "Prima16 Extras is a Prima16 tool. Other tools: Документи · RenoBudget (soon)",
    footerPdf: "Created with Prima16 Extras • extras.prima16.com",
    disclaimer:
      "This is a business template from Prima16 Extras. It is not legal, tax or accounting advice and it is not a VAT invoice.",
    formTitleCo: "Change order",
    formTitleTm: "Time & materials ticket",
    fieldNumber: "Number",
    fieldDate: "Date",
    fieldKind: "Kind",
    kindAdd: "Add",
    kindDeduct: "Deduct",
    kindSchedule: "Schedule only",
    fieldPaper: "Paper",
    fieldCurrency: "Currency",
    fieldContractor: "Contractor",
    fieldClient: "Client",
    fieldDetails: "Address, company no., phone",
    fieldSite: "Site",
    fieldContract: "Contract / quote no.",
    fieldOriginal: "Original contract",
    fieldPrev: "Previous extras",
    fieldReason: "Reason / description",
    fieldSchedule: "Schedule impact",
    fieldNotes: "Notes",
    linesTitle: "Lines",
    colDesc: "Description",
    colQty: "Qty",
    colUnit: "Unit",
    colPrice: "Unit price",
    colTotal: "Amount",
    addLine: "Line",
    fromBook: "From pricebook",
    saveBook: "Save to pricebook",
    recTitle: "Contract reconciliation",
    recOriginal: "Original contract",
    recPrev: "Previous extras",
    recThis: "This document",
    recRevised: "Revised total",
    recHidden: "No original contract amount — the block is hidden on the PDF.",
    draft: "Draft",
    finalize: "Finalise and download PDF",
    download: "Download PDF",
    print: "Print / PDF",
    saveJob: "Save to job file",
    newDoc: "New draft",
    loadSample: "Load example",
    footerOn: "Includes the Prima16 Extras footer",
    footerOff: "Clean PDF — footer removed on this device",
    unlockTitle: "Remove the footer",
    unlockOne: "Clean PDF for this type — €1.99 once",
    unlockAll: "This device, every generator — €19.99 once",
    unlockNote:
      "The order process is conducted by Paddle.com as merchant of record. 30-day refund. Does not unlock docs.prima16.com.",
    unlockDemo: "Demo payment (sandbox)",
    unlockDone: "Unlocked on this device.",
    quota: "Free final PDFs this month",
    quotaBlock: "The 2 free final PDFs for this month are used. Pay or wait until next month.",
    jobTitle: "Local job file",
    jobHint: "One unsaved-to-cloud job in this browser. Drafts do not move the total. Final documents do.",
    jobName: "Job name",
    jobRevised: "Running revised total",
    emptyJob: "No job file yet.",
    pricebookTitle: "Pricebook",
    emptyBook: "Empty pricebook. Save a line from the form.",
    pricingTitle: "Pricing",
    pricingLead:
      "Same file. The paid version drops the Prima16 Extras footer line. Pay on the download screen. Paddle.com is the merchant of record. 30-day refund.",
    faqTitle: "FAQ",
    vsTitle: "Why not Excel",
    legalTerms: "Terms",
    legalPrivacy: "Privacy",
    legalDisclaimer: "Disclaimer",
    legalRefunds: "Refunds",
    support: "Write to",
    examplesTitle: "Examples",
    blogTitle: "Notes",
    samplePdf: "Sample sheet",
  },
} as const;

export function t(locale: Locale) {
  return copy[locale];
}

export function otherLocale(locale: Locale): Locale {
  return locale === "bg" ? "en" : "bg";
}

export function pathFor(locale: Locale, rest = ""): string {
  const tail = rest ? `/${rest.replace(/^\//, "")}` : "";
  if (locale === "bg" && !rest) return "/";
  return `/${locale}${tail}`;
}
