/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as AppRouteImport } from './routes/app'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleBlogRouteImport } from './routes/$locale/blog'
import { Route as LocaleChangeOrderRouteImport } from './routes/$locale/change-order'
import { Route as LocaleChangeOrderGeneratorRouteImport } from './routes/$locale/change-order-generator'
import { Route as LocaleExamplesRouteImport } from './routes/$locale/examples'
import { Route as LocaleFaqRouteImport } from './routes/$locale/faq'
import { Route as LocalePricingRouteImport } from './routes/$locale/pricing'
import { Route as LocaleTmTicketRouteImport } from './routes/$locale/tm-ticket'
import { Route as LocaleTmTicketTemplateRouteImport } from './routes/$locale/tm-ticket-template'
import { Route as LocaleVsExcelRouteImport } from './routes/$locale/vs-excel'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as LocaleBlogSlugRouteImport } from './routes/$locale/blog.$slug'
import { Route as LocaleExamplesSlugRouteImport } from './routes/$locale/examples.$slug'
import { Route as LocaleLegalPageRouteImport } from './routes/$locale/legal.$page'
import { Route as ApiPaddleWebhookRouteImport } from './routes/api/paddle/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogRoute = LocaleBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleChangeOrderRoute = LocaleChangeOrderRouteImport.update({
  id: '/change-order',
  path: '/change-order',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleChangeOrderGeneratorRoute =
  LocaleChangeOrderGeneratorRouteImport.update({
    id: '/change-order-generator',
    path: '/change-order-generator',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleExamplesRoute = LocaleExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFaqRoute = LocaleFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePricingRoute = LocalePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTmTicketRoute = LocaleTmTicketRouteImport.update({
  id: '/tm-ticket',
  path: '/tm-ticket',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTmTicketTemplateRoute = LocaleTmTicketTemplateRouteImport.update({
  id: '/tm-ticket-template',
  path: '/tm-ticket-template',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleVsExcelRoute = LocaleVsExcelRouteImport.update({
  id: '/vs-excel',
  path: '/vs-excel',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogSlugRoute = LocaleBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleBlogRoute,
} as any)
const LocaleExamplesSlugRoute = LocaleExamplesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleExamplesRoute,
} as any)
const LocaleLegalPageRoute = LocaleLegalPageRouteImport.update({
  id: '/legal/$page',
  path: '/legal/$page',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiPaddleWebhookRoute = ApiPaddleWebhookRouteImport.update({
  id: '/api/paddle/webhook',
  path: '/api/paddle/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/app': typeof AppRoute
  '/$locale/blog': typeof LocaleBlogRouteWithChildren
  '/$locale/change-order': typeof LocaleChangeOrderRoute
  '/$locale/change-order-generator': typeof LocaleChangeOrderGeneratorRoute
  '/$locale/examples': typeof LocaleExamplesRouteWithChildren
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/tm-ticket': typeof LocaleTmTicketRoute
  '/$locale/tm-ticket-template': typeof LocaleTmTicketTemplateRoute
  '/$locale/vs-excel': typeof LocaleVsExcelRoute
  '/api/health': typeof ApiHealthRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/examples/$slug': typeof LocaleExamplesSlugRoute
  '/$locale/legal/$page': typeof LocaleLegalPageRoute
  '/api/paddle/webhook': typeof ApiPaddleWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/$locale/blog': typeof LocaleBlogRouteWithChildren
  '/$locale/change-order': typeof LocaleChangeOrderRoute
  '/$locale/change-order-generator': typeof LocaleChangeOrderGeneratorRoute
  '/$locale/examples': typeof LocaleExamplesRouteWithChildren
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/tm-ticket': typeof LocaleTmTicketRoute
  '/$locale/tm-ticket-template': typeof LocaleTmTicketTemplateRoute
  '/$locale/vs-excel': typeof LocaleVsExcelRoute
  '/api/health': typeof ApiHealthRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/examples/$slug': typeof LocaleExamplesSlugRoute
  '/$locale/legal/$page': typeof LocaleLegalPageRoute
  '/api/paddle/webhook': typeof ApiPaddleWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/app': typeof AppRoute
  '/$locale/blog': typeof LocaleBlogRouteWithChildren
  '/$locale/change-order': typeof LocaleChangeOrderRoute
  '/$locale/change-order-generator': typeof LocaleChangeOrderGeneratorRoute
  '/$locale/examples': typeof LocaleExamplesRouteWithChildren
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/tm-ticket': typeof LocaleTmTicketRoute
  '/$locale/tm-ticket-template': typeof LocaleTmTicketTemplateRoute
  '/$locale/vs-excel': typeof LocaleVsExcelRoute
  '/api/health': typeof ApiHealthRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/examples/$slug': typeof LocaleExamplesSlugRoute
  '/$locale/legal/$page': typeof LocaleLegalPageRoute
  '/api/paddle/webhook': typeof ApiPaddleWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/app'
    | '/$locale/blog'
    | '/$locale/change-order'
    | '/$locale/change-order-generator'
    | '/$locale/examples'
    | '/$locale/faq'
    | '/$locale/pricing'
    | '/$locale/tm-ticket'
    | '/$locale/tm-ticket-template'
    | '/$locale/vs-excel'
    | '/api/health'
    | '/$locale/'
    | '/$locale/blog/$slug'
    | '/$locale/examples/$slug'
    | '/$locale/legal/$page'
    | '/api/paddle/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/$locale/blog'
    | '/$locale/change-order'
    | '/$locale/change-order-generator'
    | '/$locale/examples'
    | '/$locale/faq'
    | '/$locale/pricing'
    | '/$locale/tm-ticket'
    | '/$locale/tm-ticket-template'
    | '/$locale/vs-excel'
    | '/api/health'
    | '/$locale'
    | '/$locale/blog/$slug'
    | '/$locale/examples/$slug'
    | '/$locale/legal/$page'
    | '/api/paddle/webhook'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/app'
    | '/$locale/blog'
    | '/$locale/change-order'
    | '/$locale/change-order-generator'
    | '/$locale/examples'
    | '/$locale/faq'
    | '/$locale/pricing'
    | '/$locale/tm-ticket'
    | '/$locale/tm-ticket-template'
    | '/$locale/vs-excel'
    | '/api/health'
    | '/$locale/'
    | '/$locale/blog/$slug'
    | '/$locale/examples/$slug'
    | '/$locale/legal/$page'
    | '/api/paddle/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AppRoute: typeof AppRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPaddleWebhookRoute: typeof ApiPaddleWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog': {
      id: '/$locale/blog'
      path: '/blog'
      fullPath: '/$locale/blog'
      preLoaderRoute: typeof LocaleBlogRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/change-order': {
      id: '/$locale/change-order'
      path: '/change-order'
      fullPath: '/$locale/change-order'
      preLoaderRoute: typeof LocaleChangeOrderRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/change-order-generator': {
      id: '/$locale/change-order-generator'
      path: '/change-order-generator'
      fullPath: '/$locale/change-order-generator'
      preLoaderRoute: typeof LocaleChangeOrderGeneratorRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/examples': {
      id: '/$locale/examples'
      path: '/examples'
      fullPath: '/$locale/examples'
      preLoaderRoute: typeof LocaleExamplesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/faq': {
      id: '/$locale/faq'
      path: '/faq'
      fullPath: '/$locale/faq'
      preLoaderRoute: typeof LocaleFaqRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/pricing': {
      id: '/$locale/pricing'
      path: '/pricing'
      fullPath: '/$locale/pricing'
      preLoaderRoute: typeof LocalePricingRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/tm-ticket': {
      id: '/$locale/tm-ticket'
      path: '/tm-ticket'
      fullPath: '/$locale/tm-ticket'
      preLoaderRoute: typeof LocaleTmTicketRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/tm-ticket-template': {
      id: '/$locale/tm-ticket-template'
      path: '/tm-ticket-template'
      fullPath: '/$locale/tm-ticket-template'
      preLoaderRoute: typeof LocaleTmTicketTemplateRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/vs-excel': {
      id: '/$locale/vs-excel'
      path: '/vs-excel'
      fullPath: '/$locale/vs-excel'
      preLoaderRoute: typeof LocaleVsExcelRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog/$slug': {
      id: '/$locale/blog/$slug'
      path: '/$slug'
      fullPath: '/$locale/blog/$slug'
      preLoaderRoute: typeof LocaleBlogSlugRouteImport
      parentRoute: typeof LocaleBlogRoute
    }
    '/$locale/examples/$slug': {
      id: '/$locale/examples/$slug'
      path: '/$slug'
      fullPath: '/$locale/examples/$slug'
      preLoaderRoute: typeof LocaleExamplesSlugRouteImport
      parentRoute: typeof LocaleExamplesRoute
    }
    '/$locale/legal/$page': {
      id: '/$locale/legal/$page'
      path: '/legal/$page'
      fullPath: '/$locale/legal/$page'
      preLoaderRoute: typeof LocaleLegalPageRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/paddle/webhook': {
      id: '/api/paddle/webhook'
      path: '/api/paddle/webhook'
      fullPath: '/api/paddle/webhook'
      preLoaderRoute: typeof ApiPaddleWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LocaleBlogRouteChildren {
  LocaleBlogSlugRoute: typeof LocaleBlogSlugRoute
}

const LocaleBlogRouteChildren: LocaleBlogRouteChildren = {
  LocaleBlogSlugRoute: LocaleBlogSlugRoute,
}

const LocaleBlogRouteWithChildren = LocaleBlogRoute._addFileChildren(
  LocaleBlogRouteChildren,
)

interface LocaleExamplesRouteChildren {
  LocaleExamplesSlugRoute: typeof LocaleExamplesSlugRoute
}

const LocaleExamplesRouteChildren: LocaleExamplesRouteChildren = {
  LocaleExamplesSlugRoute: LocaleExamplesSlugRoute,
}

const LocaleExamplesRouteWithChildren = LocaleExamplesRoute._addFileChildren(
  LocaleExamplesRouteChildren,
)

interface LocaleRouteChildren {
  LocaleBlogRoute: typeof LocaleBlogRouteWithChildren
  LocaleChangeOrderRoute: typeof LocaleChangeOrderRoute
  LocaleChangeOrderGeneratorRoute: typeof LocaleChangeOrderGeneratorRoute
  LocaleExamplesRoute: typeof LocaleExamplesRouteWithChildren
  LocaleFaqRoute: typeof LocaleFaqRoute
  LocalePricingRoute: typeof LocalePricingRoute
  LocaleTmTicketRoute: typeof LocaleTmTicketRoute
  LocaleTmTicketTemplateRoute: typeof LocaleTmTicketTemplateRoute
  LocaleVsExcelRoute: typeof LocaleVsExcelRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleLegalPageRoute: typeof LocaleLegalPageRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleBlogRoute: LocaleBlogRouteWithChildren,
  LocaleChangeOrderRoute: LocaleChangeOrderRoute,
  LocaleChangeOrderGeneratorRoute: LocaleChangeOrderGeneratorRoute,
  LocaleExamplesRoute: LocaleExamplesRouteWithChildren,
  LocaleFaqRoute: LocaleFaqRoute,
  LocalePricingRoute: LocalePricingRoute,
  LocaleTmTicketRoute: LocaleTmTicketRoute,
  LocaleTmTicketTemplateRoute: LocaleTmTicketTemplateRoute,
  LocaleVsExcelRoute: LocaleVsExcelRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleLegalPageRoute: LocaleLegalPageRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AppRoute: AppRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPaddleWebhookRoute: ApiPaddleWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
